### ISSUE TITLE
PHP 7.4 Notice

### ISSUE THREAD

**Issue by Mosherr** [laminas/laminas-loader#5]
In my PHP 7.4 project when using this i see the NOTICE

PHP Notice:  Trying to access array offset on value of type bool in laminas/laminas-loader/src/StandardAutoloader.php on line 319

$last = $directory[strlen($directory) - 1];

We should be checking that $directory is an array before trying to access it.

edit: check if  $directory is an array

**Comment by weierophinney** [comment]
Wrong analysis - it should be checking that `$directory` is an array.

Are you seeing anything other than the notice? is there an actual issue with how it works?

**Comment by Mosherr** [comment]
It appears to just be the Notice with no impact. even though this is feature complete shouldn't it be updated to not throw notices with newer PHP versions? Unless there is an alternative.
